import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { useState } from 'react';

export default function Index({ patients, search }) {
    const [q,setQ]=useState(search||'');
    const {data,setData,post,processing,errors,reset}=useForm({full_name:'',phone:'',gender:'',age:'',address:'',blood_group:'',emergency_contact:'',allergies:'',chronic_conditions:''});
    const submit=e=>{e.preventDefault();post(route('patients.store'),{onSuccess:()=>reset()});};
    return <AuthenticatedLayout title="مریضان"><Head title="مریضان"/><div dir="rtl" className="mx-auto max-w-7xl space-y-6 px-4 py-8">
        <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">پرونده‌های مریضان</h1><p className="text-sm text-gray-500">جستجو با نام، تلفن یا شماره پرونده</p></div><div className="flex gap-2"><input className="rounded-lg border-gray-300" value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجو..."/><button onClick={()=>router.get(route('patients.index'),{search:q})} className="rounded-lg bg-teal-600 px-4 text-white">جستجو</button></div></div>
        <form onSubmit={submit} className="grid gap-3 rounded-xl border bg-white p-5 shadow-sm md:grid-cols-4"><h2 className="md:col-span-4 font-bold">ثبت مریض جدید</h2><Input label="نام کامل" value={data.full_name} set={v=>setData('full_name',v)} error={errors.full_name}/><Input label="تلفن" value={data.phone} set={v=>setData('phone',v)}/><select className="rounded-lg border-gray-300" value={data.gender} onChange={e=>setData('gender',e.target.value)}><option value="">جنسیت</option><option value="male">مرد</option><option value="female">زن</option></select><Input label="سن" type="number" value={data.age} set={v=>setData('age',v)}/><Input label="گروپ خون" value={data.blood_group} set={v=>setData('blood_group',v)}/><Input label="تماس اضطراری" value={data.emergency_contact} set={v=>setData('emergency_contact',v)}/><Input label="آدرس" value={data.address} set={v=>setData('address',v)}/><button disabled={processing} className="rounded-lg bg-blue-600 px-4 py-2 text-white">ایجاد پرونده</button></form>
        <div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-gray-50"><tr>{['شماره پرونده','نام','تلفن','سن','عملیات'].map(x=><th className="p-3 text-right" key={x}>{x}</th>)}</tr></thead><tbody>{patients.data.map(p=><tr key={p.id} className="border-t"><td className="p-3">{p.medical_record_number||'-'}</td><td className="p-3 font-medium">{p.full_name}</td><td className="p-3">{p.phone||'-'}</td><td className="p-3">{p.age||'-'}</td><td className="p-3"><Link className="text-teal-700" href={route('patients.show',p.id)}>بازکردن پرونده</Link></td></tr>)}</tbody></table></div>
    </div></AuthenticatedLayout>;
}
function Input({label,value,set,type='text',error}){return <label className="text-sm"><span className="mb-1 block text-gray-600">{label}</span><input type={type} className="w-full rounded-lg border-gray-300" value={value} onChange={e=>set(e.target.value)}/>{error&&<span className="text-xs text-red-600">{error}</span>}</label>}
