<?php
namespace App\Http\Controllers;

use App\Models\{Admission, Appointment, Bed, ClinicalNote, LabOrder, Patient, PatientInvoice, PatientInvoicePayment, Prescription};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{Auth,DB};

class HospitalWorkflowController extends Controller
{
    public function appointment(Request $r, Patient $patient){$d=$r->validate(['doctor_id'=>'required|exists:staff,id','date'=>'required|date_format:Y/m/d','time'=>'required|date_format:H:i','duration_minutes'=>'nullable|integer|min:5|max:240','reason'=>'nullable|string|max:255']); $scheduled=jalaliToGregorian($d['date']).' '.$d['time'].':00'; $conflict=Appointment::where('doctor_id',$d['doctor_id'])->where('scheduled_at',$scheduled)->whereNotIn('status',['cancelled','no_show'])->exists(); if($conflict)return back()->withErrors(['time'=>'این زمان برای داکتر قبلاً رزرو شده است.']); $patient->appointments()->create(['doctor_id'=>$d['doctor_id'],'scheduled_at'=>$scheduled,'duration_minutes'=>$d['duration_minutes']??20,'reason'=>$d['reason']??null,'created_by'=>Auth::id()]); return back()->with('success','نوبت ثبت شد.');}
    public function appointmentStatus(Request $r, Appointment $appointment){$d=$r->validate(['status'=>'required|in:scheduled,checked_in,in_progress,completed,cancelled,no_show']);$appointment->update($d);return back();}
    public function note(Request $r, Patient $patient){$d=$r->validate(['doctor_id'=>'nullable|exists:staff,id','diagnosis'=>'nullable|string|max:255','subjective'=>'nullable|string','objective'=>'nullable|string','assessment'=>'nullable|string','plan'=>'nullable|string','vitals'=>'nullable|array']);$patient->clinicalNotes()->create($d+['created_by'=>Auth::id()]);return back()->with('success','یادداشت بالینی ثبت شد.');}
    public function labOrder(Request $r, Patient $patient){$d=$r->validate(['doctor_id'=>'nullable|exists:staff,id','ordered_at'=>'required|date_format:Y/m/d','test_ids'=>'required|array|min:1','test_ids.*'=>'exists:lab_tests,id','clinical_notes'=>'nullable|string']);DB::transaction(function()use($patient,$d){$o=$patient->labOrders()->create(['order_number'=>'LAB-'.now()->format('YmdHis').'-'.strtoupper(bin2hex(random_bytes(2))),'doctor_id'=>$d['doctor_id']??null,'ordered_at'=>$d['ordered_at'],'clinical_notes'=>$d['clinical_notes']??null,'created_by'=>Auth::id()]);foreach($d['test_ids'] as $id)$o->items()->create(['lab_test_id'=>$id]);});return back()->with('success','درخواست آزمایش ثبت شد.');}
    public function labResult(Request $r, \App\Models\LabOrderItem $item){$d=$r->validate(['result'=>'required|string|max:255','result_flag'=>'nullable|in:normal,high,low,critical','remarks'=>'nullable|string']);$item->update($d+['verified_by'=>Auth::id(),'verified_at'=>now()]);$order=$item->labOrder()->withCount(['items as pending'=>fn($q)=>$q->whereNull('result')])->first();if($order->pending===0)$order->update(['status'=>'completed']);return back()->with('success','نتیجه ثبت شد.');}
    public function prescription(Request $r, Patient $patient){$d=$r->validate(['doctor_id'=>'nullable|exists:staff,id','prescribed_at'=>'required|date_format:Y/m/d','notes'=>'nullable|string','items'=>'required|array|min:1','items.*.drug_name'=>'required|string','items.*.drug_id'=>'nullable|exists:drugs,id','items.*.dose'=>'nullable|string','items.*.frequency'=>'nullable|string','items.*.duration'=>'nullable|string','items.*.quantity'=>'required|integer|min:1','items.*.instructions'=>'nullable|string']);DB::transaction(function()use($patient,$d){$p=$patient->prescriptions()->create(['prescription_number'=>'RX-'.now()->format('YmdHis').'-'.strtoupper(bin2hex(random_bytes(2))),'doctor_id'=>$d['doctor_id']??null,'prescribed_at'=>$d['prescribed_at'],'notes'=>$d['notes']??null,'created_by'=>Auth::id()]);$p->items()->createMany($d['items']);});return back()->with('success','نسخه ثبت شد.');}
    public function admit(Request $r, Patient $patient){$d=$r->validate(['doctor_id'=>'nullable|exists:staff,id','bed_id'=>'required|exists:beds,id','reason'=>'nullable|string|max:255']);DB::transaction(function()use($patient,$d){$bed=Bed::lockForUpdate()->findOrFail($d['bed_id']);abort_if($bed->status!=='available',422,'تخت دیگر آزاد نیست.');$a=$patient->admissions()->create(['admission_number'=>'ADM-'.now()->format('YmdHis').'-'.$patient->id,'doctor_id'=>$d['doctor_id']??null,'bed_id'=>$bed->id,'admitted_at'=>now(),'reason'=>$d['reason']??null,'created_by'=>Auth::id()]);$a->transfers()->create(['to_bed_id'=>$bed->id,'started_at'=>now(),'reason'=>'پذیرش اولیه','transferred_by'=>Auth::id()]);$bed->update(['status'=>'occupied']);});return back()->with('success','مریض بستری شد.');}
    public function discharge(Request $r, Admission $admission){$d=$r->validate(['discharge_summary'=>'required|string']);DB::transaction(function()use($admission,$d){$admission->update($d+['status'=>'discharged','discharged_at'=>now()]);$admission->transfers()->whereNull('ended_at')->update(['ended_at'=>now()]);$admission->bed?->update(['status'=>'cleaning']);});app(\App\Services\PatientBillingService::class)->syncAdmission($admission->fresh());return back()->with('success','مریض ترخیص و صورتحساب به‌روزرسانی شد.');}
    public function invoice(Request $r, Patient $patient){$d=$r->validate(['invoice_date'=>'required|date_format:Y/m/d','discount'=>'nullable|integer|min:0','items'=>'required|array|min:1','items.*.service_type'=>'required|string','items.*.description'=>'required|string','items.*.quantity'=>'required|integer|min:1','items.*.unit_price'=>'required|integer|min:0']);DB::transaction(function()use($patient,$d){$subtotal=collect($d['items'])->sum(fn($x)=>$x['quantity']*$x['unit_price']);$discount=min($d['discount']??0,$subtotal);$i=$patient->invoices()->create(['invoice_number'=>'INV-'.now()->format('YmdHis').'-'.$patient->id,'invoice_date'=>$d['invoice_date'],'subtotal'=>$subtotal,'discount'=>$discount,'total_amount'=>$subtotal-$discount,'remaining_amount'=>$subtotal-$discount,'status'=>'unpaid','created_by'=>Auth::id()]);$i->items()->createMany(collect($d['items'])->map(fn($x)=>$x+['subtotal'=>$x['quantity']*$x['unit_price']])->all());});return back()->with('success','صورتحساب ایجاد شد.');}
    public function invoicePayment(Request $r, PatientInvoice $invoice){$d=$r->validate(['payment_date'=>'required|date_format:Y/m/d','amount'=>'required|integer|min:1','payment_method'=>'required|in:cash,card,bank,check,other']);if($d['amount']>$invoice->remaining_amount)return back()->withErrors(['amount'=>'مبلغ بیشتر از مانده صورتحساب است.']);DB::transaction(function()use($invoice,$d){$invoice->payments()->create($d+['receipt_number'=>'IPAY-'.now()->format('YmdHis').'-'.strtoupper(bin2hex(random_bytes(2))),'user_id'=>Auth::id()]);$paid=$invoice->payments()->sum('amount');$remaining=$invoice->total_amount-$paid;$invoice->update(['paid_amount'=>$paid,'remaining_amount'=>$remaining,'status'=>$remaining===0?'paid':'partial']);});return back()->with('success','پرداخت ثبت شد.');}
}
